import fs from "node:fs";
import * as snarkjs from "snarkjs";
import { MerkleSumTree, buildPrivateInput } from "../../sdk/dist/index.js";

const LIAB_DEPTH = 4;
const RES_DEPTH = 3;
const BUILD = "build/psolvency_demo";
const OUT_RS = "../contracts/contracts/attestar/src/fixtures.rs";

const vkey = JSON.parse(fs.readFileSync(`${BUILD}/psolvency_demo.vkey.json`, "utf8"));

const be32 = (dec) => BigInt(dec).toString(16).padStart(64, "0");
const g1 = (pt) => be32(pt[0]) + be32(pt[1]);
const g2 = (pt) => be32(pt[0][1]) + be32(pt[0][0]) + be32(pt[1][1]) + be32(pt[1][0]);
const bytes = (h) => {
  const out = [];
  for (let i = 0; i < h.length; i += 2) out.push("0x" + h.slice(i, i + 2));
  return "[" + out.join(", ") + "]";
};
const list = (hs) => `[\n        ${hs.map(bytes).join(",\n        ")}\n    ]`;

async function prove(holders, sources, onchain) {
  const liabTree = await MerkleSumTree.build(holders, LIAB_DEPTH);
  const resTree = await MerkleSumTree.build(sources, RES_DEPTH);
  const input = buildPrivateInput(holders, sources, onchain, LIAB_DEPTH, RES_DEPTH);
  const { proof, publicSignals } = await snarkjs.groth16.fullProve(
    input,
    `${BUILD}/psolvency_demo_js/psolvency_demo.wasm`,
    `${BUILD}/psolvency_demo.zkey`,
  );
  if (!(await snarkjs.groth16.verify(vkey, publicSignals, proof))) {
    throw new Error("snarkjs verify failed");
  }
  if (BigInt(publicSignals[0]) !== liabTree.root || BigInt(publicSignals[1]) !== resTree.root) {
    throw new Error("public roots do not match SDK");
  }
  if (BigInt(publicSignals[3]) !== onchain) {
    throw new Error("onchain public signal mismatch");
  }
  return {
    a: g1(proof.pi_a),
    b: g2(proof.pi_b),
    c: g1(proof.pi_c),
    pub: publicSignals.map((s) => be32(s)),
    solvent: publicSignals[2] === "1",
    onchain,
  };
}

const HOLDERS = [
  { userId: 111n, balance: 5000n },
  { userId: 222n, balance: 3000n },
  { userId: 333n, balance: 1500n },
];

const s = await prove(
  HOLDERS,
  [
    { userId: 1n, balance: 4000n },
    { userId: 2n, balance: 3000n },
  ],
  5000n,
);
const i = await prove(HOLDERS, [{ userId: 1n, balance: 1000n }], 2000n);

if (!s.solvent) throw new Error("solvent fixture is not solvent");
if (i.solvent) throw new Error("insolvent fixture is solvent");

const vk = {
  alpha: g1(vkey.vk_alpha_1),
  beta: g2(vkey.vk_beta_2),
  gamma: g2(vkey.vk_gamma_2),
  delta: g2(vkey.vk_delta_2),
  ic: vkey.IC.map(g1),
};

const rs = `// @generated by packages/circuits/scripts/encode_p.mjs - do not edit by hand.
// Real Groth16 proofs + verifying key for the PrivateSolvency(4,3,64,96) circuit.
// Public signals are [liab_root, res_root, solvent, onchain_reserves].
#![cfg(test)]

pub const ALPHA: [u8; 64] = ${bytes(vk.alpha)};
pub const BETA: [u8; 128] = ${bytes(vk.beta)};
pub const GAMMA: [u8; 128] = ${bytes(vk.gamma)};
pub const DELTA: [u8; 128] = ${bytes(vk.delta)};
pub const IC: [[u8; 64]; ${vk.ic.length}] = ${list(vk.ic)};

// Solvent fixture: onchain 5000 + offchain 7000 >= liabilities 9500.
pub const S_PROOF_A: [u8; 64] = ${bytes(s.a)};
pub const S_PROOF_B: [u8; 128] = ${bytes(s.b)};
pub const S_PROOF_C: [u8; 64] = ${bytes(s.c)};
pub const S_PUB: [[u8; 32]; 4] = ${list(s.pub)};
pub const S_LIAB_ROOT: [u8; 32] = ${bytes(s.pub[0])};
pub const S_RES_ROOT: [u8; 32] = ${bytes(s.pub[1])};
pub const S_ONCHAIN: i128 = ${s.onchain.toString()};
pub const S_SOLVENT: bool = true;

// Insolvent fixture: onchain 2000 + offchain 1000 < liabilities 9500.
pub const I_PROOF_A: [u8; 64] = ${bytes(i.a)};
pub const I_PROOF_B: [u8; 128] = ${bytes(i.b)};
pub const I_PROOF_C: [u8; 64] = ${bytes(i.c)};
pub const I_LIAB_ROOT: [u8; 32] = ${bytes(i.pub[0])};
pub const I_RES_ROOT: [u8; 32] = ${bytes(i.pub[1])};
pub const I_ONCHAIN: i128 = ${i.onchain.toString()};
pub const I_SOLVENT: bool = false;
`;

fs.writeFileSync(OUT_RS, rs);
console.log("wrote", OUT_RS);
console.log("solvent pub:", s.pub.join(","));
console.log("insolvent pub:", i.pub.join(","));
process.exit(0);
