import fs from "node:fs";
import * as snarkjs from "snarkjs";
import { MerkleSumTree, buildCircuitInput } from "../../sdk/dist/index.js";

const DEPTH = 2;
const BUILD = "build/solvency_test";
const OUT_RS = "../contracts/contracts/attestar/src/fixtures.rs";
const OUT_JSON = `${BUILD}/fixtures.json`;

const holders = [
  { userId: 111n, balance: 5000n },
  { userId: 222n, balance: 3000n },
  { userId: 333n, balance: 1500n },
];

const tree = await MerkleSumTree.build(holders, DEPTH);
const input = buildCircuitInput(holders, DEPTH);

const { proof, publicSignals } = await snarkjs.groth16.fullProve(
  input,
  `${BUILD}/solvency_test_js/solvency_test.wasm`,
  `${BUILD}/solvency_test.zkey`,
);

const vkey = JSON.parse(fs.readFileSync(`${BUILD}/solvency_test.vkey.json`, "utf8"));
if (!(await snarkjs.groth16.verify(vkey, publicSignals, proof))) {
  throw new Error("snarkjs verify failed on freshly generated proof");
}
if (BigInt(publicSignals[0]) !== tree.root || BigInt(publicSignals[1]) !== tree.total) {
  throw new Error("public signals do not match SDK root/total");
}

const be32 = (dec) => BigInt(dec).toString(16).padStart(64, "0");
const g1 = (pt) => be32(pt[0]) + be32(pt[1]);
const g2 = (pt) => be32(pt[0][1]) + be32(pt[0][0]) + be32(pt[1][1]) + be32(pt[1][0]);

const hex = {
  alpha: g1(vkey.vk_alpha_1),
  beta: g2(vkey.vk_beta_2),
  gamma: g2(vkey.vk_gamma_2),
  delta: g2(vkey.vk_delta_2),
  ic: vkey.IC.map(g1),
  proof_a: g1(proof.pi_a),
  proof_b: g2(proof.pi_b),
  proof_c: g1(proof.pi_c),
  pub: publicSignals.map((s) => be32(s)),
};

fs.writeFileSync(OUT_JSON, JSON.stringify(hex, null, 2));

const arr = (h) => {
  const out = [];
  for (let i = 0; i < h.length; i += 2) out.push("0x" + h.slice(i, i + 2));
  return "[" + out.join(", ") + "]";
};
const arrList = (hs, size) =>
  `[\n        ${hs.map(arr).join(",\n        ")}\n    ]`;

const rs = `// @generated by packages/circuits/scripts/encode.mjs - do not edit by hand.
// Real depth-2 Groth16 proof + verifying key for the Soroban verifier test.
#![cfg(test)]

pub const ALPHA: [u8; 64] = ${arr(hex.alpha)};
pub const BETA: [u8; 128] = ${arr(hex.beta)};
pub const GAMMA: [u8; 128] = ${arr(hex.gamma)};
pub const DELTA: [u8; 128] = ${arr(hex.delta)};
pub const IC: [[u8; 64]; ${hex.ic.length}] = ${arrList(hex.ic)};
pub const PROOF_A: [u8; 64] = ${arr(hex.proof_a)};
pub const PROOF_B: [u8; 128] = ${arr(hex.proof_b)};
pub const PROOF_C: [u8; 64] = ${arr(hex.proof_c)};
pub const PUB: [[u8; 32]; ${hex.pub.length}] = ${arrList(hex.pub)};
`;

fs.writeFileSync(OUT_RS, rs);
console.log("wrote", OUT_RS, "and", OUT_JSON);
console.log("public signals (root, total):", publicSignals.join(", "));
process.exit(0);
