export const ATTESTAR_ID =
  process.env.NEXT_PUBLIC_ATTESTAR_ID ?? "CD36EVFKGZH23JLRQMJZPG7XKPNO6ZVK67GHN2RQJG5VM6CVYTE2GRDH";

export const TOKEN_ID =
  process.env.NEXT_PUBLIC_TOKEN_ID ?? "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA";

export const RESERVE_HOLDER =
  process.env.NEXT_PUBLIC_RESERVE_HOLDER ?? "GDFKPIKJIY4JCYNMQ6IGX674O4HLPIPWD42LWHJSLOHAKR33IZ2VQTID";

export const SINK_ADDRESS =
  process.env.NEXT_PUBLIC_SINK_ADDRESS ?? "GD2ASCDOYWLJKUWN5KZW6WV5SARW3HKXPKBFX6Y3THDFFM4HXQXY7KKA";

export const RPC_URL = process.env.NEXT_PUBLIC_RPC_URL ?? "https://soroban-testnet.stellar.org";

export const NETWORK_PASSPHRASE =
  process.env.NEXT_PUBLIC_NETWORK_PASSPHRASE ?? "Test SDF Network ; September 2015";
